### ISSUE TITLE
Issue with awareness channel implementation (getting unexpected chars/buffer from decoder)

### ISSUE THREAD

**Issue by sbavoma** [kapv89/yjs-scalable-ws-backend#10]
hi there, as a follow up on my work with yjs websocket lib I have referred this implementation.

I have observed that my update buffer in handler consists of unexpected tokens
{�ӓ�s{"name":"Shivam","color":"rgba(224, 17, 117, 1)","alphaColor":"rgba(224, 17, 117, 0.2)","anchor":null,"focus":null}

```
    at Object.create (/code/node_modules/lib0/dist/error-8582d695.cjs:14:21)
    at Object.<anonymous> (/code/node_modules/lib0/dist/buffer-c2f560d5.cjs:927:41)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/code/node_modules/lib0/dist/encoding.cjs:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
```

Also I have observed this happens when this line is called: https://github.com/kapv89/yjs-scalable-ws-backend/blob/main/src/setupWSConnection.ts#L139

My thoughts, would be as I am testing on local my published content is directly subsribed and some OOM or buffer noise is there.

**Comment by kapv89** [comment]
hi .. trying to identify the issue ... are you running the crdt websocket server in a horizontally scaled manner such that there are multiple instances of the server runnning?

**Comment by sbavoma** [comment]
hi @kapv89 I was able to fix this issue so will close this.
But I have few issues on hand on which I would like to discuss with you regarding scaling this yjs websocket extension
